packages:
  - apps/*
  - packages/*

catalog:
  '@hookform/resolvers': 5.2.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  convex: 1.25.4
  lucide-react: 0.475.0
  react: 19.0.0
  react-dom: 19.0.0
  react-hook-form: 7.62.0
  typescript: 5.7.3
  xstate: 5.20.2
  zod: 4.0.17
