packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@hookform/resolvers": "^5.2.1"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "lucide-react": "^0.475.0"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-hook-form": "^7.62.0"
  "zod": "^4.0.17"
